apiVersion: v1
kind: Service
metadata:
  name: preserve-api-canary
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: preserve-api
    version: canary
  ports:
  - port: 8080
    targetPort: 8080
