Vagrant.configure("2") do |config|
   config.vm.box = "bento/debian-12"
   config.vm.define "nas" do |nas|
   nas.vm.hostname = "nas.local"
   nas.vm.network "private_network", ip: "192.168.10.10"
   nas.vm.provider "vmware_desktop" do |vmware|
      vmware.gui = ENV['VAGRANT_GUI'] == 'true' 
      vmware.memory = 1512
      vmware.linked_clone = false
      disk1 = File.expand_path("disque2.vmdk", File.dirname(__FILE__))
      disk2 = File.expand_path("disque1.vmdk", File.dirname(__FILE__))
      disk3 = File.expand_path("disque3.vmdk", File.dirname(__FILE__))

      vmware.vmx["sata0:2.present"]  = "TRUE"
      vmware.vmx["sata0:2.fileName"] = disk1
      vmware.vmx["sata0:2.redo"]     = ""

      vmware.vmx["sata0:3.present"]  = "TRUE"
      vmware.vmx["sata0:3.fileName"] = disk2
      vmware.vmx["sata0:3.redo"]     = ""

      vmware.vmx["sata0:4.present"]  = "TRUE"
      vmware.vmx["sata0:4.fileName"] = disk3
      vmware.vmx["sata0:4.redo"]     = ""
      end
      config.vm.provision "shell", inline: <<-SHELL
         apt-get update -y
      SHELL
      end

   config.vm.define "ldap" do |ldap|
      ldap.vm.hostname = "ldap.local"
      ldap.vm.network "private_network", ip: "192.168.10.20"
      ldap.vm.provider "vmware_desktop" do |vmware|
         vmware.gui = ENV['VAGRANT_GUI'] == 'true' 
         vmware.memory = 512
         vmware.linked_clone = false
      end
      config.vm.provision "shell", inline: <<-SHELL
      apt-get update -y
      apt-get install -y debconf-utils
      SHELL
   end

   config.vm.define "backup" do |backup|
      backup.vm.hostname = "backup.local"
      backup.vm.network "private_network", ip: "192.168.10.30"
      backup.vm.provider "vmware_desktop" do |vmware|
         vmware.gui = ENV['VAGRANT_GUI'] == 'true' 
         vmware.memory = 1024
         vmware.linked_clone = false
      end
      config.vm.provision "shell", inline: <<-SHELL
         apt-get update -y
      SHELL
      end
end
