Vagrant.configure("2") do |config|
    config.vm.box = "bento/debian-12"
    config.ssh.shell = "bash -l"
    config.vm.define "db" do |db|
    db.vm.hostname = "db.local"
    db.vm.network "private_network", ip: "192.168.10.10"
    db.vm.provider "vmware_desktop" do |vmware|
        vmware.gui = ENV['VAGRANT_GUI'] == 'true' 
        vmware.memory = 1024
        vmware.linked_clone = false
    end
    config.vm.provision "shell", inline: <<-SHELL
        apt-get update -y
        apt-get install -y python3 openssl
        cd /vagrant/script
        sudo python3 config-server.py
        SHELL
    end
end