vm_num = 2
Vagrant.configure("2") do |config|
    config.vm.box = "bento/debian-12"
    config.ssh.shell = "bash -l"
    config.vm.provision "shell", inline: <<-SHELL
    apt-get update -y
    apt-get install -y python3 openssl
    cd /vagrant/script
    sudo python3 config_server.py
    SHELL
    config.vm.define "db" do |db|
        db.vm.hostname = "db.local"
        db.vm.network "private_network", ip: "192.168.10.10"
        db.vm.provider "vmware_desktop" do |vmware|
            vmware.gui = ENV['VAGRANT_GUI'] == 'true'
            vmware.memory = 1024
            vmware.linked_clone = false
        end
    end
    config.vm.define "haproxy" do |haproxy|
        haproxy.vm.hostname = "haproxy.local"
        haproxy.vm.network "private_network", ip: "192.168.10.20"
        haproxy.vm.provider "vmware_desktop" do |vmware|
            vmware.gui = ENV['VAGRANT_GUI'] == 'true'
            vmware.memory = 512
            vmware.linked_clone = false
        end
        haproxy.vm.provision "file",
            source: "haproxy/haproxy.cfg",
            destination: "/tmp/haproxy.cfg"
        haproxy.vm.provision "shell", inline: <<-SHELL
            apt-get install -y haproxy
            cp /tmp/haproxy.cfg /etc/haproxy/haproxy.cfg
            systemctl enable haproxy
            systemctl restart haproxy
        SHELL
    end
    config.vm.define "k3s" do |k3s|
        k3s.vm.hostname = "k3s.local"
        k3s.vm.network "private_network", ip: "192.168.10.30"
        k3s.vm.provider "vmware_desktop" do |vmware|
            vmware.gui = ENV['VAGRANT_GUI'] == 'true'
            vmware.memory = 512
            vmware.linked_clone = false
        end
    end
    (1..vm_num) .each do |n|
        config.vm.define "vault-#{n}" do |vault|
            vault.vm.hostname = "vault-#{n}.local"
            vault.vm.network "private_network", ip: "192.168.10.#{n+10}"
            vault.vm.provider "vmware_desktop" do |vmware|
                vmware.gui = ENV['VAGRANT_GUI'] == 'true'
                vmware.memory = 512
                vmware.linked_clone = false
            end
            vault.vm.provision "shell", inline: <<-SHELL
                echo "export VAULT_ADDR=http://192.168.10.#{n+10}:8200" >> /etc/profile.d/vault.sh
            SHELL
        end
    end
end
