Vagrant.configure("2") do |config|
  config.vm.box = "bento/debian-12"
  config.vm.define "asterisk" do |asterisk|
    asterisk.vm.hostname = "asterisk.local"
    asterisk.vm.network "private_network", ip: "192.168.10.10"
    asterisk.vm.provider "vmware_desktop" do |vmware|
      vmware.gui = ENV['VAGRANT_GUI'] == 'true'
      vmware.memory = 2048
      vmware.cpus = 2
      vmware.linked_clone = false
    end
    asterisk.vm.provision "shell", inline: <<-SHELL
      apt update -y
    SHELL
  end
  config.vm.define "vpn-gateway" do |vpn|
    vpn.vm.hostname = "vpn-gateway.local"
    vpn.vm.network "private_network", ip: "192.168.10.40"
    vpn.vm.network "forwarded_port", guest: 51820, host: 51821, protocol: "udp"
    vpn.vm.provider "vmware_desktop" do |vmware|
      vmware.gui = ENV['VAGRANT_GUI'] == 'true'
      vmware.memory = 512
      vmware.cpus = 1
      vmware.linked_clone = false
    end
    vpn.vm.provision "shell", inline: <<-SHELL
     apt update
     apt install -y wireguard
    SHELL
  end
  config.vm.define "a2billing" do |a2b|
    a2b.vm.hostname = "a2billing.local"
    a2b.vm.box = "bento/debian-12"
    a2b.vm.network "private_network", ip: "192.168.10.20"
    a2b.vm.provider "vmware_desktop" do |vmware|
      vmware.gui = ENV['VAGRANT_GUI'] == 'true'
      vmware.memory = 1048
      vmware.cpus = 2
      vmware.linked_clone = false
    end
    a2b.vm.provision "shell", inline: <<-SHELL
      apt update
    SHELL
  end
  config.vm.define "db" do |db|
    db.vm.hostname = "db.local"
    db.vm.box = "bento/debian-12"
    db.vm.network "private_network", ip: "192.168.10.30"
    db.vm.provider "vmware_desktop" do |vmware|
      vmware.gui = ENV['VAGRANT_GUI'] == 'true'
      vmware.memory = 1048
      vmware.cpus = 1
      vmware.linked_clone = false
    end
    db.vm.provision "shell", inline: <<-SHELL
      apt update
    SHELL
  end
end
