Vagrant.configure("2") do |config|
  config.vm.box = "bento/debian-12"
  config.vm.define "asterisk" do |asterisk|
    asterisk.vm.hostname = "asterisk.local"
    asterisk.vm.network "private_network", ip: "192.168.10.10"
    asterisk.vm.provider "vmware_desktop" do |vmware|
      vmware.gui = ENV['VAGRANT_GUI'] == 'true'
      vmware.memory = 2048
      vmware.cpus = 2
      vmware.linked_clone = false
    end
    asterisk.vm.provision "shell", inline: <<-SHELL
      apt-get update -y
    SHELL
  end
end