Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/jammy64"

  config.vm.define "ca" do |ca|

    ca.vm.hostname = "ca.com"

    ca.vm.network "private_network",
      ip: "192.168.56.10"

    ca.vm.synced_folder "./shared", "/shared"

    ca.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
      vb.name = "ca"
    end

    ca.vm.provision "shell", inline: <<-SHELL

      apt-get install -y openssl

    SHELL

  end

  config.vm.define "frontend" do |frontend|

    frontend.vm.hostname = "app.com"

    frontend.vm.network "private_network",
      ip: "192.168.56.30"

    frontend.vm.synced_folder "./shared", "/shared"

    frontend.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
      vb.name = "frontend"
    end

    frontend.vm.provision "shell", inline: <<-SHELL

      apt-get install -y nginx

      cat > /var/www/html/index.html <<EOF
<!DOCTYPE html>
<html lang="fr">
<head>
<meta charset="UTF-8">
<title>app.com</title>
</head>
<body>
  <div class="box">
    <h1> web application</h1>
    <p> App behind reverse proxy HTTPS</p>
  </div>
</body>
</html>
EOF

      systemctl enable nginx
      systemctl restart nginx

    SHELL

  end
  
  config.vm.define "proxy" do |proxy|

    proxy.vm.hostname = "proxy.com"

    proxy.vm.network "private_network",
      ip: "192.168.56.20"

    proxy.vm.synced_folder "./shared", "/shared"

    proxy.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
      vb.name = "proxy"
    end

    proxy.vm.provision "shell", inline: <<-SHELL

      apt-get install -y nginx openssl
      
    SHELL

  end

end
