---
- name: Install and Config Asterisk
  hosts: asterisk-lab
  become: true
  tags: asterisk-installation
  gather_facts: false
  roles:
    - role: asterisk-installation

- name: Configuration of the wireguard server
  hosts: vpn-gateway-lab
  become: true
  tags: wg-config
  gather_facts: false
  roles:
    - role: config_vpn

- name: Asterisk extensions and pjsip configuration
  hosts: asterisk-lab
  become: true
  tags: asterisk-config
  gather_facts: false
  roles:
    - role: config_asterisk

